<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 2016/12/23
 * Time: 11:14
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserInfo extends Model
{
    // 指定表名
    protected $table = "user";

    // 指定id
    protected $primaryKey = "id";

    // 允许批量赋值的字段
    protected $fillable = ['name', 'password', 'state', 'create_id', 'create_time'];

    // 不允许批量赋值的字段
    protected  $guarded = [];

    // 自动维护时间戳
    public $timestamps = false;

    protected function getDateFormat(){
        return time();
    }

    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }
}